language: ruby
sudo: false

rvm:
  - 2.2

services:
  - docker
  
before_install:
  - docker-compose -v
  - docker-compose build

script:
  - docker-compose run web rake spec
  
after_install:
  - docker-compose down