version: '2'
services:
  redis:
    image: redis:3.0.7
  web:
    build: .
    environment:
      - REDIS_URL=redis://redis
      - VIRTUAL_HOST=wastebits.docker
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - redis
  workers:
    build: .
    command: bundle exec sidekiq
    environment:
      - REDIS_URL=redis://redis
    volumes:
      - .:/app
    depends_on:
      - redis
      - web